### ISSUE TITLE
gsm2016_components.h5 doesn't load

### ISSUE THREAD

**Issue by JLBLine** [telegraphic/PyGSM#1]
Hey guys,

Was keen to try out the 2016 version of the gsm, however I cannot use GlobalSkyModel2016(), it gives me the error:

*\* lots of error messages etc etc **

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/tmp/pip_build_root/h5py/h5py/_objects.c:2577)()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/tmp/pip_build_root/h5py/h5py/_objects.c:2536)()

h5py/h5f.pyx in h5py.h5f.open (/tmp/pip_build_root/h5py/h5py/h5f.c:1811)()

IOError: Unable to open file (Unable to find a valid file signature)

---

I traced this down to just not being able to open gsm2016_components.h5, i.e. doing the below seems impossible

import h5py
f = h5py.File('/usr/local/PyGSM/pygsm/gsm2016_components.h5','r')

To idiot check myself, I was successfully able to load the old file:

f = h5py.File('/usr/local/PyGSM/pygsm/gsm_components.h5','r')

**Comment by nithyanandan** [comment]
Pasting here the response of the author which helped me fix the problem with gsm2016.

> If using the 2016 model, I caution/note that I am unconvinced that the flux scale is correct (i.e. in agreement with the older GSM), but I have not followed this up with Zheng et al.
>
> This or a similar issue came up with another user, and I think it was to do with not having the github large file support system installed. So, can you please either:
>
> * Download the file manually from https://github.com/telegraphic/PyGSM/blob/master/pygsm/gsm2016_components.h5
and then copy it over and reinstall
> or
> * Install git-lfs and re-clone
>
> and see if that fixes it.

Copying the file to pygsm folder or wherever the data files for the package are kept and reinstalling should fix the GSM 2016 module

**Comment by adriaanph** [comment]
i ran into the same problem, either of the two suggested bullet points work.

**Comment by telegraphic** [comment]
Closing -- I uploaded the component files to zenodo and updated the readme
