### ISSUE TITLE
Not able to pull gsm2016_components.h5

### ISSUE THREAD

**Issue by utkarshgiri** [telegraphic/PyGSM#11]
Hi,

I am trying to clone your repo with git-lfs but for some reason, I am getting the following error:
```
batch response: This repository is over its data quota. Purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/telegraphic/PyGSM.git/info/lfs'
```
Could you please help me with this issue!

**Comment by MilesCranmer** [comment]
Hi Utkarsh,
I can email you my copy of this file.
Cheers,
Miles

**Comment by utkarshgiri** [comment]
Hi Miles,

Thanks a lot. That would be big help.

**Comment by MilesCranmer** [comment]
For anybody else who is having a similar issue, here is a hosted version of the file: https://drive.google.com/open?id=1yUAhg3xc7FWHenTQRsdf8xUJDBR-3qfr

**Comment by telegraphic** [comment]
Thanks Miles, this is due to git's large file support (LFS), which has a 1 GB cap. We could also try hosting the files on zenodo.

**Comment by telegraphic** [comment]
Closing -- files now hosted on Zenodo too!
