### ISSUE TITLE
updated GSM2016 files available

### ISSUE THREAD

**Issue by adriaanph** [telegraphic/PyGSM#3]
6 months ago jeff zhen updated his component maps with the following note "_corrected haslam resolution from 48" to 56" to match updated manuscript_" [jeff's github repository](https://github.com/jeffzhen/gsm2016).

to avoid confusion (it took me a day) please update your models.

**Comment by telegraphic** [comment]
Good spot, thanks for raising an issue. Hope to get to this soon!

**Comment by telegraphic** [comment]
OK, I have (finally) updated the underlying components file, so closing this issue.
